name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "50 6 * * *"
  workflow_dispatch:

env:
  rust_toolchain: nightly
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - default
    steps:
      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
          components: rustfmt, clippy, rust-src

      - name: Install libdbus
        run: sudo apt-get install -y libdbus-1-dev

      - name: Install libavahi-client
        run: sudo apt-get install -y libavahi-client-dev

      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Build | Fmt Check
        run: cd rs-matter-embassy; cargo fmt -- --check

      - name: Build | Clippy
        run: cd rs-matter-embassy; cargo clippy --no-deps -- -Dwarnings

      - name: Build | Compile
        run: cd rs-matter-embassy; cargo build

      - name: Examples-Build | Fmt Check
        run: cd examples/esp32; cargo fmt -- --check

      - name: Examples-Build | Clippy
        run: cd examples/esp32; cargo clippy --no-deps -- -Dwarnings

      - name: Examples-Build | Compile
        run: cd examples/esp32; cargo build
